[colors.primary]
background = '#fef9f0'
foreground = '#1d1c16'
 
[colors.cursor]
text = '#1d1c16'
cursor = '#49473a' 
 
[colors.vi_mode_cursor]
text = '#fef9f0'
cursor = '#686000' 
 
[colors.search.matches]
foreground = '#e8e2d0' 
background = '#406652' 
 
[colors.search.focused_match]
foreground = '#e8e2d0' 
background = '#686000' 
 
[colors.footer_bar]
foreground = '#e8e2d0' 
background = '#32302a' 
 
[colors.hints.start]
foreground = '#e8e2d0' 
background = '#635f41' 
 
[colors.hints.end]
foreground = '#e8e2d0' 
background = '#635f41' 
 
[colors.selection]
text = '#fef9f0'
background = '#686000'
 
 
[colors.normal]
black = '#181818' 
red = '#ba1a1a' 
green = '#686000' 
yellow = '#d7c950' 
blue = '#686000' 
magenta = '#406652' 
cyan = '#635f41' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 