[colors.primary]
background = '#f8f9fa'
foreground = '#42474c'

[colors.cursor]
text = '#f8f9fa'
cursor = '#ffaa33'

[colors.vi_mode_cursor]
text = '#f8f9fa'
cursor = '#e65050'

[colors.search.matches]
foreground = '#e4e6e9'
background = '#55b4d4'

[colors.search.focused_match]
foreground = '#e4e6e9'
background = '#e65050'

[colors.footer_bar]
foreground = '#e4e6e9'
background = '#232629'

[colors.hints.start]
foreground = '#e4e6e9'
background = '#ff8f40'

[colors.hints.end]
foreground = '#e4e6e9'
background = '#ff8f40'

[colors.selection]
text = '#f8f9fa'
background = '#035bd6'


[colors.normal]
black   = '#000000'
red     = '#eca944'
green   = '#ea6c6d'
yellow  = '#6cbf43'
blue    = '#3199e1'
magenta = '#9e75c7'
cyan    = '#46ba94'
white   = '#bababa'


[colors.bright]
black   = '#686868'
red     = '#f2ae49'
green   = '#f07171'
yellow  = '#86b300'
blue    = '#399ee6'
magenta = '#a37acc'
cyan    = '#4cbf99'
white   = '#d1d1d1'


[colors.dim]
black   = '#000000'
red     = '#eca944'
green   = '#ea6c6d'
yellow  = '#6cbf43'
blue    = '#3199e1'
magenta = '#9e75c7'
cyan    = '#46ba94'
white   = '#bababa'
