general {
    lock_cmd = pidof hyprlock || (hyprlock & sleep 0.5 && hyprctl dispatch dpms off)
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    # Note: this setting is set by default, but i kept it here just to remember 
    # that hypridle respects dbus_inhibit
    ignore_dbus_inhibit = false
}

listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 160
    on-timeout = loginctl lock-session
}

listener {
    timeout = 175
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 200
    on-timeout = systemctl suspend
}
