-- Generated by nwg-displays on 2026-08-14 at 18:29:17. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3200x2000@120.0",
    position = "1841x1080",
    scale = 2.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "1722x0",
    scale = 1.0
})
