# --- THEME SELECTOR ---

# OPTION 1: Libadwaita Neutral (Grey/Graphite)
$main_bg            = rgba(1e1e1eff)
$main_bg_alt        = rgba(242424ff)
$main_fg            = rgba(ffffffff)
$active_border_1    = rgba(b0b0b0ff) 
$active_border_2    = rgba(666666ff) 
$inactive_border    = rgba(303030ff) 
$accent_color       = rgba(b0b0b0ff)
$warning_color      = rgba(f5c211ff)
$gtk_theme_env      = adw-gtk3-dark

# OPTION 2: Gruvbox Material
# $main_bg            = rgba(282828ff)
# $main_bg_alt        = rgba(1d2021ff)
# $main_fg            = rgba(d4be98ff)
# $active_border_1    = rgba(e78a4eff)
# $active_border_2    = rgba(d8a657ff)
# $inactive_border    = rgba(282828ff)
# $accent_color       = rgba(e78a4eff)
# $warning_color      = rgba(d8a657ff)
# $gtk_theme_env      = Gruvbox-Material-Dark

# --- SYSTEM ENVS ---

env = GDK_BACKEND,wayland
env = GTK_THEME,$gtk_theme_env
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = ADW_DISABLE_PORTAL,1

# Dark mode settings
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme '$gtk_theme_env'

# --- AUTOSTART ---

exec-once = dunst
exec-once = hyprpaper
exec-once = vicinae server
exec-once = hypridle
exec-once = udiskie
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets,ssh,pkcs11
exec-once = dbus-update-activation-environment --all

# --- INPUT ---

input {
    kb_layout = us, ru
    kb_options = grp:win_space_toggle
    sensitivity = 0.3

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

animations {
    enabled = false
}

# --- LOOK & FEEL ---

general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10
    
    # Используем унифицированные переменные
    col.active_border = $active_border_1 $active_border_2 45deg
    col.inactive_border = $inactive_border
}

group {
    col.border_active = $active_border_1
    col.border_inactive = $inactive_border

    groupbar {
        enabled = true
        font_family = "Open Sans"
        font_size = 10
        height = 10
        render_titles = true
        
        col.active = $active_border_1
        col.inactive = $main_bg_alt
        col.locked_active = $warning_color
    }
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.90
    
    blur {
        enabled = false
    }
    
    shadow {
        enabled = false
    }
}

misc {
    vfr = true
}

xwayland {
    enabled = false    
}

# --- DEVICES ---

device {
    name = huion-huion-tablet_h420x-pen
    output = HDMI-A-1
}
