# --- THEME VARIABLES ---
# OPTION 1: Libadwaita Neutral (Grey/Graphite)
$main_bg            = rgba(1e1e1eff)
$main_bg_alt        = rgba(242424ff)
$main_fg            = rgba(ffffffff)
$active_border_1    = rgba(b0b0b0ff) 
$active_border_2    = rgba(666666ff) 
$inactive_border    = rgba(303030ff) 
$accent_color       = rgba(b0b0b0ff)
$warning_color      = rgba(f5c211ff)
$gtk_theme_env      = adw-gtk3-dark

# --- Hyprland ecosystem autostart ---
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- pypr
exec-once = uwsm app -- hyprpm reload

# --- INPUT ---
input {
    kb_layout = us, ru
    kb_options = grp:win_space_toggle
    sensitivity = 0.3

    touchpad {
        tap-to-click = true
        natural_scroll = true
        disable_while_typing = true
    }
}

gestures {
    gesture = 2, pinchin, cursorZoom, 2.0, mult
    gesture = 2, pinchout, cursorZoom, 1.0
}

animations {
    enabled = true
    bezier = quick, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 1.5, quick, popin 80%
    animation = workspaces, 1, 1.2, quick, slide
    animation = fade, 1, 1.5, quick
}

# --- LOOK & FEEL ---
general {
    border_size = 2
    gaps_in = 5
    gaps_out = 10
    
    col.active_border = $active_border_1 $active_border_2 45deg
    col.inactive_border = $inactive_border
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.95
    direction = right
    focus_fit_method = 0
}

group {
    col.border_active = $active_border_1
    col.border_inactive = $inactive_border

    groupbar {
        enabled = true
        font_family = "Open Sans"
        font_size = 10
        height = 10
        render_titles = true

        col.active = $active_border_1
        col.inactive = $main_bg_alt
        col.locked_active = $warning_color
    }
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.90
    
    blur {
        enabled = false
    }
    
    shadow {
        enabled = false
    }
}

misc {
    vfr = true
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

plugin {
    hyprexpo {
        columns = 3
        bg_col = rgba(1e1e1e99)
        workspace_method = center current
        skip_empty = true
    }
}

xwayland {
    enabled = false    
}

# --- DEVICES ---
device {
    name = huion-huion-tablet_h420x-pen
    output = HDMI-A-1
}
